[package]
name = "buildlike-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2.8"
geo = "0.18.0"

[dev-dependencies]
eframe = "0.15.0"